name: Python LEI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/ci.txt
        pip install -e .
    - name: Download Data
      run: python -c "from python_lei.utils import Download; Download(_is_actions=True)"

    - name: Test
      run: python -m pytest tests/

    - name: Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        pip install codecov
        codecov

  CD:
    needs: CI
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: PyPi Deploy preparation
      run: |
        pip install --upgrade setuptools wheel
        python setup.py sdist bdist_wheel --universal
    - name: PyPi Deploy
      uses: pypa/gh-action-pypi-publish@v1.0.0a0
      with:
        user: ${{ secrets.PYPI_USER }}
        password: ${{ secrets.PYPI_PASSWORD }}